name: 'Standard'
description: 'Provides a standard site with commonly used features pre-configured.'
type: 'Site'
recipes:
  - basic_block_type
  - article_comment
  - article_tags
  - feedback_contact_form
  - article_content_type
  - page_content_type
  - basic_html_format_editor
  - full_html_format_editor
  - core_recommended_performance
  - core_recommended_maintenance
  - core_recommended_admin_theme
  - core_recommended_front_end_theme
  # Provides a fallback text format which is available to all users.
  - restricted_html_format
install:
  - field
  - file
  - image
  - help
  - search
  - history
  - config
  - contextual
  - menu_link_content
  - datetime
  - menu_ui
  - options
  - toolbar
  - field_ui
  - views_ui
  - link
  - shortcut
  - default_content
config:
  import:
    claro:
      - block.block.claro_help
    file:
      - views.view.files
    help:
      - search.page.help_search
      - block.block.claro_help_search
    image:
      - image.style.large
      - image.style.thumbnail
    node:
      - core.entity_view_mode.node.search_index
      - core.entity_view_mode.node.search_result
      - search.page.node_search
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    olivero:
      - block.block.olivero_help
      - block.block.olivero_search_form_narrow
      - block.block.olivero_search_form_wide
      - block.block.olivero_syndicate
    user:
      - core.entity_view_mode.user.compact
      - search.page.user_search
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online
    shortcut:
      - shortcut.set.default
  actions:
    core.menu.static_menu_link_overrides:
      simple_config_update:
        definitions:
          contact__site_page:
            menu_name: footer
            parent: ''
            weight: 0
            expanded: false
            enabled: true
    node.settings:
      simple_config_update:
        # @todo Remove `langcode` once https://drupal.org/i/3427564 lands.
        langcode: en
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access shortcuts'
        - 'delete own files'
        - 'search content'
    user.role.content_editor:
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access contextual links'
        - 'access files overview'
        - 'access toolbar'
        - 'administer url aliases'
        - 'create url aliases'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view own unpublished content'
        - 'view the administration theme'
        - 'create article content'
        - 'delete article revisions'
        - 'delete own article content'
        - 'edit own article content'
        - 'create page content'
        - 'delete page revisions'
        - 'delete own page content'
        - 'edit own page content'
        - 'edit own comments'
        - 'create terms in tags'
        - 'edit terms in tags'
    user.role.*:
      grantPermissions:
        # This recipe assumes all published content should be publicly accessible.
        - 'access content'
        - 'search content'
    user.settings:
      simple_config_update:
        verify_mail: true
        register: visitors_admin_approval
        cancel_method: user_cancel_block
